version: '3'

services:
  nginx:
    container_name: childfoundation_nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - childfoundation_static_volume:/childfoundation/static
      - childfoundation_files_volume:/childfoundation/files
      - childfoundation_ssl_volume:/childfoundation/ssl
      - ./ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./ssl/private.key:/etc/nginx/ssl/private.key
    networks:
      - childfoundation_nginx_network
      - host_web_server

volumes:
  childfoundation_static_volume:
    external: true
  childfoundation_files_volume:
    external: true
  childfoundation_ssl_volume:
    external: true
networks:
  childfoundation_nginx_network:
    external: true
  host_web_server:
    external: true